spring:
  application:
    name: discodeit
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나의 최대 크기
      max-request-size: 30MB # 한 번에 최대 업로드 가능 용량

discodeit:
  storage:
    type: database
    path: ${spring.datasource.url}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 4.1.1
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}

logging:
  level:
    root: info
