server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.sprint.mission.discodeit: info
management:
  endpoint:
    health:
      show-details: never
