server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.sprint.mission.discodeit: debug
management:
  endpoint:
    health:
      show-details: always
